import { Inter } from "next/font/google";
import "./globals.css";
import "../public/css/app.min.css"
import "../public/css/fontawesome.min.css"
import "../public/css/style.css"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MBP Game",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
